# Generated by Django 3.1 on 2021-03-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=60, unique=True, verbose_name='Correo electronico'),
        ),
    ]
