# Generated by Django 3.1 on 2021-04-11 01:50

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('profesion', models.CharField(max_length=30)),
                ('xp', models.IntegerField()),
                ('telefono', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="El número de telefono debe ingresarse en el formato: '+999999999'. hasta 15 digitos permitidos.", regex='^\\+?1?\\d{9,15}$')])),
                ('idiomas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('descripcion', models.CharField(max_length=500)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
