# Generated by Django 3.1 on 2021-04-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20210424_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
    ]
