# Generated by Django 3.1 on 2021-04-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20210424_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='presupuesto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
