# Generated by Django 3.1 on 2021-04-30 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20210424_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=40)),
                ('solicitud', models.CharField(max_length=320)),
                ('noLeido', models.BooleanField(default=True)),
                ('borrado', models.BooleanField(default=False)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.freelancer')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.proyecto')),
            ],
        ),
    ]
