# Generated by Django 3.1 on 2021-04-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_proyecto_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='moneda',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
