# Generated by Django 3.1 on 2021-04-30 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_notificaciones'),
        ('usuarios', '0008_proyecto_moneda'),
    ]

    operations = [
    ]
