# Generated by Django 3.1 on 2021-05-01 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_merge_20210430_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrataciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaContratacion', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.freelancer')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.proyecto')),
            ],
        ),
    ]
